# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapclientplugins\geometricfitstep\qt\geometricfitwidget.ui'
#
# Created: Wed May  6 22:29:36 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_GeometricFitWidget(object):
    def setupUi(self, GeometricFitWidget):
        GeometricFitWidget.setObjectName("GeometricFitWidget")
        GeometricFitWidget.resize(1718, 1394)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeometricFitWidget.sizePolicy().hasHeightForWidth())
        GeometricFitWidget.setSizePolicy(sizePolicy)
        GeometricFitWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalLayout = QtGui.QHBoxLayout(GeometricFitWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dockWidget = QtGui.QDockWidget(GeometricFitWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(779, 1069))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.identifier_label = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identifier_label.sizePolicy().hasHeightForWidth())
        self.identifier_label.setSizePolicy(sizePolicy)
        self.identifier_label.setObjectName("identifier_label")
        self.verticalLayout.addWidget(self.identifier_label)
        self.steps_groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.steps_groupBox.sizePolicy().hasHeightForWidth())
        self.steps_groupBox.setSizePolicy(sizePolicy)
        self.steps_groupBox.setObjectName("steps_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.steps_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stepsAddDelete_frame = QtGui.QFrame(self.steps_groupBox)
        self.stepsAddDelete_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stepsAddDelete_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.stepsAddDelete_frame.setObjectName("stepsAddDelete_frame")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.stepsAddDelete_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.stepsAddAlign_pushButton = QtGui.QPushButton(self.stepsAddDelete_frame)
        self.stepsAddAlign_pushButton.setObjectName("stepsAddAlign_pushButton")
        self.horizontalLayout_10.addWidget(self.stepsAddAlign_pushButton)
        self.stepsAddConfig_pushButton = QtGui.QPushButton(self.stepsAddDelete_frame)
        self.stepsAddConfig_pushButton.setObjectName("stepsAddConfig_pushButton")
        self.horizontalLayout_10.addWidget(self.stepsAddConfig_pushButton)
        self.stepsAddFit_pushButton = QtGui.QPushButton(self.stepsAddDelete_frame)
        self.stepsAddFit_pushButton.setObjectName("stepsAddFit_pushButton")
        self.horizontalLayout_10.addWidget(self.stepsAddFit_pushButton)
        self.stepsDelete_pushButton = QtGui.QPushButton(self.stepsAddDelete_frame)
        self.stepsDelete_pushButton.setObjectName("stepsDelete_pushButton")
        self.horizontalLayout_10.addWidget(self.stepsDelete_pushButton)
        self.verticalLayout_2.addWidget(self.stepsAddDelete_frame)
        self.steps_listView = QtGui.QListView(self.steps_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.steps_listView.sizePolicy().hasHeightForWidth())
        self.steps_listView.setSizePolicy(sizePolicy)
        self.steps_listView.setObjectName("steps_listView")
        self.verticalLayout_2.addWidget(self.steps_listView)
        self.stepedit_scrollArea = QtGui.QScrollArea(self.steps_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepedit_scrollArea.sizePolicy().hasHeightForWidth())
        self.stepedit_scrollArea.setSizePolicy(sizePolicy)
        self.stepedit_scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.stepedit_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.stepedit_scrollArea.setWidgetResizable(True)
        self.stepedit_scrollArea.setObjectName("stepedit_scrollArea")
        self.stepedit_scrollAreaWidgetContents = QtGui.QWidget()
        self.stepedit_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 671, 949))
        self.stepedit_scrollAreaWidgetContents.setObjectName("stepedit_scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.stepedit_scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.config_groupBox = QtGui.QGroupBox(self.stepedit_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_groupBox.sizePolicy().hasHeightForWidth())
        self.config_groupBox.setSizePolicy(sizePolicy)
        self.config_groupBox.setObjectName("config_groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.config_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.configInitial_groupBox = QtGui.QGroupBox(self.config_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configInitial_groupBox.sizePolicy().hasHeightForWidth())
        self.configInitial_groupBox.setSizePolicy(sizePolicy)
        self.configInitial_groupBox.setObjectName("configInitial_groupBox")
        self.formLayout = QtGui.QFormLayout(self.configInitial_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.configModelCoordinates_label = QtGui.QLabel(self.configInitial_groupBox)
        self.configModelCoordinates_label.setObjectName("configModelCoordinates_label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.configModelCoordinates_label)
        self.configModelCoordinates_fieldChooser = FieldChooserWidget(self.configInitial_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configModelCoordinates_fieldChooser.sizePolicy().hasHeightForWidth())
        self.configModelCoordinates_fieldChooser.setSizePolicy(sizePolicy)
        self.configModelCoordinates_fieldChooser.setObjectName("configModelCoordinates_fieldChooser")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.configModelCoordinates_fieldChooser)
        self.configDataCoordinates_label = QtGui.QLabel(self.configInitial_groupBox)
        self.configDataCoordinates_label.setObjectName("configDataCoordinates_label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.configDataCoordinates_label)
        self.configMarkerGroup_label = QtGui.QLabel(self.configInitial_groupBox)
        self.configMarkerGroup_label.setObjectName("configMarkerGroup_label")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.configMarkerGroup_label)
        self.configDataCoordinates_fieldChooser = FieldChooserWidget(self.configInitial_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configDataCoordinates_fieldChooser.sizePolicy().hasHeightForWidth())
        self.configDataCoordinates_fieldChooser.setSizePolicy(sizePolicy)
        self.configDataCoordinates_fieldChooser.setObjectName("configDataCoordinates_fieldChooser")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.configDataCoordinates_fieldChooser)
        self.configMarkerGroup_fieldChooser = FieldChooserWidget(self.configInitial_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configMarkerGroup_fieldChooser.sizePolicy().hasHeightForWidth())
        self.configMarkerGroup_fieldChooser.setSizePolicy(sizePolicy)
        self.configMarkerGroup_fieldChooser.setObjectName("configMarkerGroup_fieldChooser")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.configMarkerGroup_fieldChooser)
        self.verticalLayout_4.addWidget(self.configInitial_groupBox)
        self.configProjection_groupBox = QtGui.QGroupBox(self.config_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configProjection_groupBox.sizePolicy().hasHeightForWidth())
        self.configProjection_groupBox.setSizePolicy(sizePolicy)
        self.configProjection_groupBox.setObjectName("configProjection_groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.configProjection_groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.configProjectionCentreGroups_checkBox = QtGui.QCheckBox(self.configProjection_groupBox)
        self.configProjectionCentreGroups_checkBox.setObjectName("configProjectionCentreGroups_checkBox")
        self.verticalLayout_5.addWidget(self.configProjectionCentreGroups_checkBox)
        self.verticalLayout_4.addWidget(self.configProjection_groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.config_groupBox)
        self.align_groupBox = QtGui.QGroupBox(self.stepedit_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.align_groupBox.sizePolicy().hasHeightForWidth())
        self.align_groupBox.setSizePolicy(sizePolicy)
        self.align_groupBox.setObjectName("align_groupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.align_groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.alignMarkers_checkBox = QtGui.QCheckBox(self.align_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignMarkers_checkBox.sizePolicy().hasHeightForWidth())
        self.alignMarkers_checkBox.setSizePolicy(sizePolicy)
        self.alignMarkers_checkBox.setObjectName("alignMarkers_checkBox")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.alignMarkers_checkBox)
        self.alignRotation_label = QtGui.QLabel(self.align_groupBox)
        self.alignRotation_label.setObjectName("alignRotation_label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.alignRotation_label)
        self.alignRotation_lineEdit = QtGui.QLineEdit(self.align_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignRotation_lineEdit.sizePolicy().hasHeightForWidth())
        self.alignRotation_lineEdit.setSizePolicy(sizePolicy)
        self.alignRotation_lineEdit.setObjectName("alignRotation_lineEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.alignRotation_lineEdit)
        self.alignScale_label = QtGui.QLabel(self.align_groupBox)
        self.alignScale_label.setObjectName("alignScale_label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.alignScale_label)
        self.alignScale_lineEdit = QtGui.QLineEdit(self.align_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignScale_lineEdit.sizePolicy().hasHeightForWidth())
        self.alignScale_lineEdit.setSizePolicy(sizePolicy)
        self.alignScale_lineEdit.setObjectName("alignScale_lineEdit")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.alignScale_lineEdit)
        self.alignTranslation_label = QtGui.QLabel(self.align_groupBox)
        self.alignTranslation_label.setObjectName("alignTranslation_label")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.alignTranslation_label)
        self.alignTranslation_lineEdit = QtGui.QLineEdit(self.align_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignTranslation_lineEdit.sizePolicy().hasHeightForWidth())
        self.alignTranslation_lineEdit.setSizePolicy(sizePolicy)
        self.alignTranslation_lineEdit.setObjectName("alignTranslation_lineEdit")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.alignTranslation_lineEdit)
        self.verticalLayout_3.addWidget(self.align_groupBox)
        self.fit_groupBox = QtGui.QGroupBox(self.stepedit_scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fit_groupBox.sizePolicy().hasHeightForWidth())
        self.fit_groupBox.setSizePolicy(sizePolicy)
        self.fit_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fit_groupBox.setFlat(False)
        self.fit_groupBox.setCheckable(False)
        self.fit_groupBox.setObjectName("fit_groupBox")
        self.formLayout_3 = QtGui.QFormLayout(self.fit_groupBox)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.fitStrainPenalty_label = QtGui.QLabel(self.fit_groupBox)
        self.fitStrainPenalty_label.setObjectName("fitStrainPenalty_label")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.fitStrainPenalty_label)
        self.fitStrainPenalty_lineEdit = QtGui.QLineEdit(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitStrainPenalty_lineEdit.sizePolicy().hasHeightForWidth())
        self.fitStrainPenalty_lineEdit.setSizePolicy(sizePolicy)
        self.fitStrainPenalty_lineEdit.setObjectName("fitStrainPenalty_lineEdit")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.fitStrainPenalty_lineEdit)
        self.fitCurvaturePenalty_label = QtGui.QLabel(self.fit_groupBox)
        self.fitCurvaturePenalty_label.setObjectName("fitCurvaturePenalty_label")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.fitCurvaturePenalty_label)
        self.fitCurvaturePenalty_lineEdit = QtGui.QLineEdit(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitCurvaturePenalty_lineEdit.sizePolicy().hasHeightForWidth())
        self.fitCurvaturePenalty_lineEdit.setSizePolicy(sizePolicy)
        self.fitCurvaturePenalty_lineEdit.setObjectName("fitCurvaturePenalty_lineEdit")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.fitCurvaturePenalty_lineEdit)
        self.fitUpdateReferenceState_checkBox = QtGui.QCheckBox(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitUpdateReferenceState_checkBox.sizePolicy().hasHeightForWidth())
        self.fitUpdateReferenceState_checkBox.setSizePolicy(sizePolicy)
        self.fitUpdateReferenceState_checkBox.setObjectName("fitUpdateReferenceState_checkBox")
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.fitUpdateReferenceState_checkBox)
        self.fitIterations_label = QtGui.QLabel(self.fit_groupBox)
        self.fitIterations_label.setObjectName("fitIterations_label")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.fitIterations_label)
        self.fitIterations_spinBox = QtGui.QSpinBox(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitIterations_spinBox.sizePolicy().hasHeightForWidth())
        self.fitIterations_spinBox.setSizePolicy(sizePolicy)
        self.fitIterations_spinBox.setMinimum(1)
        self.fitIterations_spinBox.setMaximum(1000)
        self.fitIterations_spinBox.setObjectName("fitIterations_spinBox")
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.fitIterations_spinBox)
        self.fitEdgeDiscontinuityPenalty_label = QtGui.QLabel(self.fit_groupBox)
        self.fitEdgeDiscontinuityPenalty_label.setObjectName("fitEdgeDiscontinuityPenalty_label")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.fitEdgeDiscontinuityPenalty_label)
        self.fitEdgeDiscontinuityPenalty_lineEdit = QtGui.QLineEdit(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitEdgeDiscontinuityPenalty_lineEdit.sizePolicy().hasHeightForWidth())
        self.fitEdgeDiscontinuityPenalty_lineEdit.setSizePolicy(sizePolicy)
        self.fitEdgeDiscontinuityPenalty_lineEdit.setObjectName("fitEdgeDiscontinuityPenalty_lineEdit")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.fitEdgeDiscontinuityPenalty_lineEdit)
        self.fitMarkerWeight_label = QtGui.QLabel(self.fit_groupBox)
        self.fitMarkerWeight_label.setObjectName("fitMarkerWeight_label")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.fitMarkerWeight_label)
        self.fitMarkerWeight_lineEdit = QtGui.QLineEdit(self.fit_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitMarkerWeight_lineEdit.sizePolicy().hasHeightForWidth())
        self.fitMarkerWeight_lineEdit.setSizePolicy(sizePolicy)
        self.fitMarkerWeight_lineEdit.setObjectName("fitMarkerWeight_lineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.fitMarkerWeight_lineEdit)
        self.verticalLayout_3.addWidget(self.fit_groupBox)
        self.stepedit_scrollArea.setWidget(self.stepedit_scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.stepedit_scrollArea)
        self.verticalLayout.addWidget(self.steps_groupBox)
        self.display_groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_groupBox.sizePolicy().hasHeightForWidth())
        self.display_groupBox.setSizePolicy(sizePolicy)
        self.display_groupBox.setObjectName("display_groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.display_groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.displayMisc_frame = QtGui.QFrame(self.display_groupBox)
        self.displayMisc_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayMisc_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayMisc_frame.setObjectName("displayMisc_frame")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.displayMisc_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.displayAxes_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAxes_checkBox.setObjectName("displayAxes_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAxes_checkBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_7.addWidget(self.displayMisc_frame)
        self.displayMarker_frame = QtGui.QFrame(self.display_groupBox)
        self.displayMarker_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayMarker_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayMarker_frame.setObjectName("displayMarker_frame")
        self.gridLayout = QtGui.QGridLayout(self.displayMarker_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.displayMarkerDataNames_checkBox = QtGui.QCheckBox(self.displayMarker_frame)
        self.displayMarkerDataNames_checkBox.setObjectName("displayMarkerDataNames_checkBox")
        self.gridLayout.addWidget(self.displayMarkerDataNames_checkBox, 0, 1, 1, 1)
        self.displayMarkerDataPoints_checkBox = QtGui.QCheckBox(self.displayMarker_frame)
        self.displayMarkerDataPoints_checkBox.setObjectName("displayMarkerDataPoints_checkBox")
        self.gridLayout.addWidget(self.displayMarkerDataPoints_checkBox, 0, 0, 1, 1)
        self.displayMarkerNames_checkBox = QtGui.QCheckBox(self.displayMarker_frame)
        self.displayMarkerNames_checkBox.setObjectName("displayMarkerNames_checkBox")
        self.gridLayout.addWidget(self.displayMarkerNames_checkBox, 3, 1, 1, 1)
        self.displayMarkerPoints_checkBox = QtGui.QCheckBox(self.displayMarker_frame)
        self.displayMarkerPoints_checkBox.setObjectName("displayMarkerPoints_checkBox")
        self.gridLayout.addWidget(self.displayMarkerPoints_checkBox, 3, 0, 1, 1)
        self.displayMarkerDataProjections_checkBox = QtGui.QCheckBox(self.displayMarker_frame)
        self.displayMarkerDataProjections_checkBox.setObjectName("displayMarkerDataProjections_checkBox")
        self.gridLayout.addWidget(self.displayMarkerDataProjections_checkBox, 0, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.displayMarker_frame)
        self.displayData_frame = QtGui.QFrame(self.display_groupBox)
        self.displayData_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayData_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayData_frame.setObjectName("displayData_frame")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.displayData_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.displayDataPoints_checkBox = QtGui.QCheckBox(self.displayData_frame)
        self.displayDataPoints_checkBox.setObjectName("displayDataPoints_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataPoints_checkBox)
        self.displayDataProjections_checkBox = QtGui.QCheckBox(self.displayData_frame)
        self.displayDataProjections_checkBox.setObjectName("displayDataProjections_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataProjections_checkBox)
        self.displayDataProjectionPoints_checkBox = QtGui.QCheckBox(self.displayData_frame)
        self.displayDataProjectionPoints_checkBox.setObjectName("displayDataProjectionPoints_checkBox")
        self.horizontalLayout_9.addWidget(self.displayDataProjectionPoints_checkBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.displayData_frame)
        self.displayNodes_frame = QtGui.QFrame(self.display_groupBox)
        self.displayNodes_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodes_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodes_frame.setObjectName("displayNodes_frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.displayNodes_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.displayNodePoints_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        self.displayNodePoints_checkBox.setObjectName("displayNodePoints_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodePoints_checkBox)
        self.displayNodeNumbers_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeNumbers_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeNumbers_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeNumbers_checkBox.setObjectName("displayNodeNumbers_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeNumbers_checkBox)
        self.displayNodeDerivatives_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivatives_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivatives_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivatives_checkBox.setObjectName("displayNodeDerivatives_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeDerivatives_checkBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.displayNodes_frame)
        self.displayNodeDerivativeLabels_frame = QtGui.QFrame(self.display_groupBox)
        self.displayNodeDerivativeLabels_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodeDerivativeLabels_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodeDerivativeLabels_frame.setObjectName("displayNodeDerivativeLabels_frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.displayNodeDerivativeLabels_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.displayNodeDerivativeLabelsD1_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD1_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD1_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD1_checkBox.setObjectName("displayNodeDerivativeLabelsD1_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD1_checkBox)
        self.displayNodeDerivativeLabelsD2_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD2_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD2_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD2_checkBox.setObjectName("displayNodeDerivativeLabelsD2_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD2_checkBox)
        self.displayNodeDerivativeLabelsD3_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD3_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD3_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD3_checkBox.setObjectName("displayNodeDerivativeLabelsD3_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD3_checkBox)
        self.displayNodeDerivativeLabelsD12_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD12_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD12_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD12_checkBox.setObjectName("displayNodeDerivativeLabelsD12_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD12_checkBox)
        self.displayNodeDerivativeLabelsD13_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD13_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD13_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD13_checkBox.setObjectName("displayNodeDerivativeLabelsD13_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD13_checkBox)
        self.displayNodeDerivativeLabelsD23_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD23_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD23_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD23_checkBox.setObjectName("displayNodeDerivativeLabelsD23_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD23_checkBox)
        self.displayNodeDerivativeLabelsD123_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD123_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD123_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD123_checkBox.setObjectName("displayNodeDerivativeLabelsD123_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD123_checkBox)
        self.verticalLayout_7.addWidget(self.displayNodeDerivativeLabels_frame)
        self.displayElements_frame = QtGui.QFrame(self.display_groupBox)
        self.displayElements_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayElements_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayElements_frame.setObjectName("displayElements_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.displayElements_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.displayElementNumbers_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        self.displayElementNumbers_checkBox.setObjectName("displayElementNumbers_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementNumbers_checkBox)
        self.displayElementAxes_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayElementAxes_checkBox.sizePolicy().hasHeightForWidth())
        self.displayElementAxes_checkBox.setSizePolicy(sizePolicy)
        self.displayElementAxes_checkBox.setObjectName("displayElementAxes_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementAxes_checkBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_7.addWidget(self.displayElements_frame)
        self.displayLines_frame = QtGui.QFrame(self.display_groupBox)
        self.displayLines_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayLines_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayLines_frame.setObjectName("displayLines_frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.displayLines_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.displayLines_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        self.displayLines_checkBox.setObjectName("displayLines_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLines_checkBox)
        self.displayLinesExterior_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLinesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displayLinesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displayLinesExterior_checkBox.setObjectName("displayLinesExterior_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLinesExterior_checkBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_7.addWidget(self.displayLines_frame)
        self.displaySurfaces_frame = QtGui.QFrame(self.display_groupBox)
        self.displaySurfaces_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displaySurfaces_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displaySurfaces_frame.setObjectName("displaySurfaces_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.displaySurfaces_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displaySurfaces_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        self.displaySurfaces_checkBox.setObjectName("displaySurfaces_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfaces_checkBox)
        self.displaySurfacesExterior_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesExterior_checkBox.setObjectName("displaySurfacesExterior_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesExterior_checkBox)
        self.displaySurfacesTranslucent_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesTranslucent_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesTranslucent_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesTranslucent_checkBox.setObjectName("displaySurfacesTranslucent_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesTranslucent_checkBox)
        self.displaySurfacesWireframe_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesWireframe_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesWireframe_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesWireframe_checkBox.setObjectName("displaySurfacesWireframe_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesWireframe_checkBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_7.addWidget(self.displaySurfaces_frame)
        self.verticalLayout.addWidget(self.display_groupBox)
        self.bottom_frame = QtGui.QFrame(self.dockWidgetContents)
        self.bottom_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAll_pushButton = QtGui.QPushButton(self.bottom_frame)
        self.viewAll_pushButton.setObjectName("viewAll_pushButton")
        self.horizontalLayout_2.addWidget(self.viewAll_pushButton)
        self.done_pushButton = QtGui.QPushButton(self.bottom_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.done_pushButton.sizePolicy().hasHeightForWidth())
        self.done_pushButton.setSizePolicy(sizePolicy)
        self.done_pushButton.setObjectName("done_pushButton")
        self.horizontalLayout_2.addWidget(self.done_pushButton)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dockWidget)
        self.alignmentsceneviewerwidget = AlignmentSceneviewerWidget(GeometricFitWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignmentsceneviewerwidget.sizePolicy().hasHeightForWidth())
        self.alignmentsceneviewerwidget.setSizePolicy(sizePolicy)
        self.alignmentsceneviewerwidget.setObjectName("alignmentsceneviewerwidget")
        self.horizontalLayout.addWidget(self.alignmentsceneviewerwidget)

        self.retranslateUi(GeometricFitWidget)
        QtCore.QMetaObject.connectSlotsByName(GeometricFitWidget)

    def retranslateUi(self, GeometricFitWidget):
        GeometricFitWidget.setWindowTitle(QtGui.QApplication.translate("GeometricFitWidget", "Geometric Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("GeometricFitWidget", "Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.identifier_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Identifier", None, QtGui.QApplication.UnicodeUTF8))
        self.steps_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsAddAlign_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "Add Align", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsAddConfig_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "Add Config", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsAddFit_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "Add Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.stepsDelete_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.config_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.configInitial_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Initial", None, QtGui.QApplication.UnicodeUTF8))
        self.configModelCoordinates_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Model coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.configDataCoordinates_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Data coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.configMarkerGroup_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker group:", None, QtGui.QApplication.UnicodeUTF8))
        self.configProjection_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.configProjectionCentreGroups_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Centre groups", None, QtGui.QApplication.UnicodeUTF8))
        self.align_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Align", None, QtGui.QApplication.UnicodeUTF8))
        self.alignMarkers_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Align markers", None, QtGui.QApplication.UnicodeUTF8))
        self.alignRotation_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignScale_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignTranslation_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Translation:", None, QtGui.QApplication.UnicodeUTF8))
        self.fit_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitStrainPenalty_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Strain penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitCurvaturePenalty_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Curvature penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitUpdateReferenceState_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Update reference state", None, QtGui.QApplication.UnicodeUTF8))
        self.fitIterations_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitEdgeDiscontinuityPenalty_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Edge discontinuity penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitMarkerWeight_label.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.display_groupBox.setTitle(QtGui.QApplication.translate("GeometricFitWidget", "Display:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAxes_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerDataNames_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker data names", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerDataPoints_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker data points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerNames_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker names", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerPoints_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayMarkerDataProjections_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Marker projections", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataPoints_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Data points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataProjections_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Data projections", None, QtGui.QApplication.UnicodeUTF8))
        self.displayDataProjectionPoints_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Data projection points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodePoints_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Node points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeNumbers_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Node numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivatives_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Node derivatives", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD1_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD2_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D2", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD3_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D3", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD12_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D12", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD13_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D13", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD23_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D23", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD123_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "D123", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementNumbers_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Element numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementAxes_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Element axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLines_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLinesExterior_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfaces_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesExterior_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesTranslucent_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Transluc.", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesWireframe_checkBox.setText(QtGui.QApplication.translate("GeometricFitWidget", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAll_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.done_pushButton.setText(QtGui.QApplication.translate("GeometricFitWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from .alignmentsceneviewerwidget import AlignmentSceneviewerWidget
from opencmiss.zincwidgets.fieldchooserwidget import FieldChooserWidget
